### ISSUE TITLE
Client is targeting non-existing route on TriggersController for adding a trigger with unique name

### ISSUE THREAD

**Issue by stanke86** [jobbrIO/jobbr-webapi#13]
Client is targeting 
` var url = $"jobs/{uniqueName}/triggers/{triggerDto.Id}";`
insted of 
` var url = $"jobs/{uniqueName}/triggers";`

https://github.com/jobbrIO/jobbr-webapi/blob/2743e4d2720a1de63f1a990fbcd96b05343b6019/source/Jobbr.Client/JobbrClient.cs#L79

Also this method is not covered with tests

**Comment by linkdotnet** [comment]
Fixed. Releasing fix with v2.0.1
